version: '3'
services:
  interface:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    image: go-gin-example:latest
    container_name: go-gin-example-service
    environment:
      ENV: dev
    ports:
      - "8080:8080"
    dns:
      - 114.114.114.114
